platform :ios,'7.0'

target 'UIDictionaryKitDemo' do
source 'https://github.com/CocoaPods/Specs.git'  
pod 'Masonry'
pod 'HBDictionaryKit',:path=>"../HBDictionaryKit.podspec"
pod "HBKit", :path=> '/Users/boo/Documents/demo/HBFastTableViewCotroller/HBKit.podspec'

end
#注释
